version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: infobus-cms-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: better-sqlite3
      DATABASE_FILENAME: ./data/data.db
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      HOST: 0.0.0.0
      PORT: 1337
    ports:
      - '1337:1337'
    volumes:
      # Persist data and uploads
      - ./data:/opt/app/data
      - ./database:/opt/app/database
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - strapi-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/_health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: infobus-cms-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - strapi
    networks:
      - strapi-network
    profiles:
      - with-nginx

networks:
  strapi-network:
    driver: bridge